name: Simple Test

on:
  push:
    branches: [ main, testing_cursor ]
  pull_request:
    branches: [ main, testing_cursor ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      shell: bash
      run: |
        set -o pipefail
        npm test 2>&1 | tee test-output.txt

    - name: Intentionally fail step (for testing)
      run: |
        echo "Forcing failure on testing_cursor branch"
        exit 1

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simple-test-logs
        path: test-output.txt
        if-no-files-found: ignore
        retention-days: 3
